development: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: legapedia_development
  pool: 5
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: legapedia_test
  pool: 5
  username: root
  password: root
  host: localhost

production:
  <<: *default
  database: legapedia_prod
  host: localhost
